
export default function BottleContent() {
    return (
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Scelerisque eu ultrices vitae auctor. Lobortis elementum nibh tellus molestie nunc. Lectus nulla at volutpat diam ut venenatis tellus in metus. Vitae congue mauris rhoncus aenean vel. Massa sed elementum tempus egestas sed sed risus pretium quam. Consequat id porta nibh venenatis cras sed felis eget. Suspendisse faucibus interdum posuere lorem ipsum dolor. Porta non pulvinar neque laoreet suspendisse. Quis lectus nulla at volutpat diam ut venenatis tellus. Felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Habitant morbi tristique senectus et netus. Urna et pharetra pharetra massa massa ultricies mi quis. Porta lorem mollis aliquam ut porttitor leo. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Amet nulla facilisi morbi tempus. Eget mauris pharetra et ultrices. Felis bibendum ut tristique et egestas quis ipsum suspendisse.

        Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt. Nunc non blandit massa enim nec dui nunc. Dolor sit amet consectetur adipiscing elit ut aliquam. Turpis tincidunt id aliquet risus feugiat in ante metus dictum. Fermentum iaculis eu non diam phasellus vestibulum lorem sed. Elementum tempus egestas sed sed risus. Posuere ac ut consequat semper viverra. Lectus vestibulum mattis ullamcorper velit sed. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Facilisi etiam dignissim diam quis. Dictum varius duis at consectetur lorem. Ut diam quam nulla porttitor massa id. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Id volutpat lacus laoreet non curabitur. Ultricies mi eget mauris pharetra et ultrices neque ornare.
        
        Vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Curabitur vitae nunc sed velit dignissim sodales. Ipsum consequat nisl vel pretium lectus quam id leo. Neque laoreet suspendisse interdum consectetur libero id. Feugiat nisl pretium fusce id velit ut tortor pretium. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Cras sed felis eget velit aliquet sagittis. Vel quam elementum pulvinar etiam non quam lacus. Viverra maecenas accumsan lacus vel facilisis volutpat est velit egestas. Vulputate mi sit amet mauris commodo quis imperdiet. Adipiscing diam donec adipiscing tristique risus. Diam quis enim lobortis scelerisque fermentum. Arcu non odio euismod lacinia at quis risus sed. Cursus risus at ultrices mi. Facilisi cras fermentum odio eu feugiat pretium. Ac tortor dignissim convallis aenean. Et malesuada fames ac turpis egestas. Egestas integer eget aliquet nibh praesent tristique. Nunc vel risus commodo viverra maecenas accumsan.
        
        Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Vulputate mi sit amet mauris commodo quis imperdiet. Feugiat in ante metus dictum at tempor commodo. Tempor id eu nisl nunc mi ipsum faucibus. Ac turpis egestas maecenas pharetra convallis posuere morbi. Leo integer malesuada nunc vel risus. Accumsan tortor posuere ac ut consequat. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Ipsum consequat nisl vel pretium lectus. Et tortor at risus viverra adipiscing.
        
        Cras tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Tellus mauris a diam maecenas sed. Enim eu turpis egestas pretium aenean. Eu facilisis sed odio morbi quis commodo odio aenean sed. Aenean euismod elementum nisi quis eleifend quam adipiscing vitae proin. Aliquam purus sit amet luctus venenatis lectus magna fringilla. Malesuada fames ac turpis egestas sed tempus. Fringilla urna porttitor rhoncus dolor purus non enim praesent. Laoreet sit amet cursus sit. Augue ut lectus arcu bibendum at varius vel pharetra vel. At varius vel pharetra vel turpis. Lobortis mattis aliquam faucibus purus in massa tempor. Vitae auctor eu augue ut lectus arcu. Ut placerat orci nulla pellentesque dignissim enim sit amet venenatis. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada.</div>
    )
}