export const pinnedImagesData = [
    // {
    //     title: "liv-pointing",
    //     imageTitle: "liv-pointing.png",
    //     altText: "Liv pointing towards the camera",
    //     imageHeight: "300px",
    //     percentFromTop: "25%",
    //     percentFromLeft: "40%"
    // },
    // {
    //     title: "liv-in-blue",
    //     imageTitle: "liv-in-blue.png",
    //     altText: "Liv in a blue coat looking at the camera",
    //     imageHeight: "160px",
    //     percentFromTop: "30%",
    //     percentFromLeft: "30%"
    // },
    {
        title: "bottle",
        altText: "a blue water bottle",
        imageHeight: "75px",
        percentFromTop: "16.5%",
        percentFromLeft: "75%",
        xsHeight: "75px",
        xsPercentFromTop: "16.5%",
        xsPercentFromLeft: "75%",
        smHeight: "",
        smPercentFromTop: "",
        smPercentFromLeft: "",
        mdHeight: "",
        mdPercentFromTop: "",
        mdPercentFromLeft: "",
        lgHeight: "",
        lgPercentFromTop: "",
        lgPercentFromLeft: "",
        xlHeight: "",
        xlPercentFromTop: "",
        xlPercentFromLeft: ""
    },
    {
        title: "record-player",
        altText: "a blue water bottle",
        imageHeight: "90px",
        percentFromTop: "28%",
        percentFromLeft: "60%",
        xsHeight: "90px",
        xsPercentFromTop: "28%",
        xsPercentFromLeft: "60%",
        smHeight: "",
        smPercentFromTop: "",
        smPercentFromLeft: "",
        mdHeight: "",
        mdPercentFromTop: "",
        mdPercentFromLeft: "",
        lgHeight: "",
        lgPercentFromTop: "",
        lgPercentFromLeft: "",
        xlHeight: "",
        xlPercentFromTop: "",
        xlPercentFromLeft: ""
    },
    {
        title: "sewing-machine",
        altText: "a red industrial sewing machine",
        imageHeight: "404px",
        percentFromTop: "47%",
        percentFromLeft: "0%",
        xsHeight: "404px",
        xsPercentFromTop: "47%",
        xsPercentFromLeft: "0%",
        smHeight: "",
        smPercentFromTop: "",
        smPercentFromLeft: "",
        mdHeight: "",
        mdPercentFromTop: "",
        mdPercentFromLeft: "",
        lgHeight: "",
        lgPercentFromTop: "",
        lgPercentFromLeft: "",
        xlHeight: "",
        xlPercentFromTop: "",
        xlPercentFromLeft: "",
    },
    {
        title: "fabric",
        altText: "a red industrial sewing machine",
        imageHeight: "100px",
        percentFromTop: "42%",
        percentFromLeft: "42%",
        xsHeight: "100px",
        xsPercentFromTop: "42%",
        xsPercentFromLeft: "42%",
        smHeight: "",
        smPercentFromTop: "",
        smPercentFromLeft: "",
        mdHeight: "",
        mdPercentFromTop: "",
        mdPercentFromLeft: "",
        lgHeight: "",
        lgPercentFromTop: "",
        lgPercentFromLeft: "",
        xlHeight: "",
        xlPercentFromTop: "",
        xlPercentFromLeft: ""
    },
    {
        title: "headphones",
        altText: "a red industrial sewing machine",
        imageHeight: "90px",
        percentFromTop: "27%",
        percentFromLeft: "47%",
        xsHeight: "90px",
        xsPercentFromTop: "27%",
        xsPercentFromLeft: "47%",
        smHeight: "",
        smPercentFromTop: "",
        smPercentFromLeft: "",
        mdHeight: "",
        mdPercentFromTop: "",
        mdPercentFromLeft: "",
        lgHeight: "",
        lgPercentFromTop: "",
        lgPercentFromLeft: "",
        xlHeight: "",
        xlPercentFromTop: "",
        xlPercentFromLeft: ""
    },
    {
        title: "laptop",
        altText: "a red industrial sewing machine",
        imageHeight: "87px",
        percentFromTop: "28%",
        percentFromLeft: "30%",
        xsHeight: "87px",
        xsPercentFromTop: "28%",
        xsPercentFromLeft: "30%",
        smHeight: "",
        smPercentFromTop: "",
        smPercentFromLeft: "",
        mdHeight: "",
        mdPercentFromTop: "",
        mdPercentFromLeft: "",
        lgHeight: "",
        lgPercentFromTop: "",
        lgPercentFromLeft: "",
        xlHeight: "",
        xlPercentFromTop: "",
        xlPercentFromLeft: ""
    },
    {
        title: "newspaper",
        altText: "a red industrial sewing machine",
        imageHeight: "50px",
        percentFromTop: "33%",
        percentFromLeft: "75%",
        xsHeight: "50px",
        xsPercentFromTop: "33%",
        xsPercentFromLeft: "75%",
        smHeight: "",
        smPercentFromTop: "",
        smPercentFromLeft: "",
        mdHeight: "",
        mdPercentFromTop: "",
        mdPercentFromLeft: "",
        lgHeight: "",
        lgPercentFromTop: "",
        lgPercentFromLeft: "",
        xlHeight: "",
        xlPercentFromTop: "",
        xlPercentFromLeft: ""
    },
    {
        title: "games",
        altText: "a red industrial sewing machine",
        imageHeight: "65px",
        percentFromTop: "45%",
        percentFromLeft: "65%",
        xsHeight: "50px",
        xsPercentFromTop: "33%",
        xsPercentFromLeft: "7%",
        smHeight: "",
        smPercentFromTop: "",
        smPercentFromLeft: "",
        mdHeight: "",
        mdPercentFromTop: "",
        mdPercentFromLeft: "",
        lgHeight: "",
        lgPercentFromTop: "",
        lgPercentFromLeft: "",
        xlHeight: "",
        xlPercentFromTop: "",
        xlPercentFromLeft: ""
    }

]
