export const pinnedImagesData = [
    // {
    //     title: "bottle",
    //     altText: "a blue water bottle",
    //     imageHeight: "120px",
    //     percentFromTop: "16.5%",
    //     percentFromLeft: "75%",
    //     xsHeight: "75px",
    //     xsPercentFromTop: "16.5%",
    //     xsPercentFromLeft: "75%",
    //     smHeight: "100px",
    //     smPercentFromTop: "16.5%",
    //     smPercentFromLeft: "75%",
    //     mdHeight: "120px",
    //     mdPercentFromTop: "",
    //     mdPercentFromLeft: "",
    //     lgHeight: "",
    //     lgPercentFromTop: "",
    //     lgPercentFromLeft: "",
    //     xlHeight: "",
    //     xlPercentFromTop: "",
    //     xlPercentFromLeft: ""
    // },
    {
        title: "bottle",
        altText: "a blue water bottle",
        imageHeightMultiplier: ".12",
        percentFromTop: "16.5%",
        percentFromLeft: "75%",
    },
    // {
    //     title: "record-player",
    //     altText: "a blue water bottle",
    //     imageHeight: "140px",
    //     percentFromTop: "28%",
    //     percentFromLeft: "60%",
    //     xsHeight: "90px",
    //     xsPercentFromTop: "28%",
    //     xsPercentFromLeft: "60%",
    //     smHeight: "120px",
    //     smPercentFromTop: "28%",
    //     smPercentFromLeft: "60%",
    //     mdHeight: "140px",
    //     mdPercentFromTop: "",
    //     mdPercentFromLeft: "",
    //     lgHeight: "",
    //     lgPercentFromTop: "",
    //     lgPercentFromLeft: "",
    //     xlHeight: "",
    //     xlPercentFromTop: "",
    //     xlPercentFromLeft: ""
    // },
    // {
    //     title: "sewing-machine",
    //     altText: "a red industrial sewing machine",
    //     imageHeight: "536.576px",
    //     percentFromTop: "47%",
    //     percentFromLeft: "0%",
    //     xsHeight: "404px",
    //     xsPercentFromTop: "47%",
    //     xsPercentFromLeft: "0%",
    //     smHeight: "511px",
    //     smPercentFromTop: "",
    //     smPercentFromLeft: "",
    //     mdHeight: "621px",
    //     mdPercentFromTop: "",
    //     mdPercentFromLeft: "",
    //     lgHeight: "",
    //     lgPercentFromTop: "",
    //     lgPercentFromLeft: "",
    //     xlHeight: "",
    //     xlPercentFromTop: "",
    //     xlPercentFromLeft: "",
    // },
    {
        title: "sewing-machine",
        altText: "a red industrial sewing machine",
        imageHeightMultiplier: ".524",
        percentFromTop: "47%",
        percentFromLeft: "0%",
    },
    // {
    //     title: "fabric",
    //     altText: "pink fabric",
    //     imageHeight: "155px",
    //     percentFromTop: "42%",
    //     percentFromLeft: "42%",
    //     xsHeight: "100px",
    //     xsPercentFromTop: "42%",
    //     xsPercentFromLeft: "42%",
    //     smHeight: "125px",
    //     smPercentFromTop: "42%",
    //     smPercentFromLeft: "42%",
    //     mdHeight: "155px",
    //     mdPercentFromTop: "",
    //     mdPercentFromLeft: "",
    //     lgHeight: "",
    //     lgPercentFromTop: "",
    //     lgPercentFromLeft: "",
    //     xlHeight: "",
    //     xlPercentFromTop: "",
    //     xlPercentFromLeft: ""
    // },
    // {
    //     title: "headphones",
    //     altText: "yellow headphones",
    //     imageHeight: "140px",
    //     percentFromTop: "27%",
    //     percentFromLeft: "47%",
    //     xsHeight: "90px",
    //     xsPercentFromTop: "27%",
    //     xsPercentFromLeft: "47%",
    //     smHeight: "115px",
    //     smPercentFromTop: "27%",
    //     smPercentFromLeft: "47%",
    //     mdHeight: "140px",
    //     mdPercentFromTop: "",
    //     mdPercentFromLeft: "",
    //     lgHeight: "",
    //     lgPercentFromTop: "",
    //     lgPercentFromLeft: "",
    //     xlHeight: "",
    //     xlPercentFromTop: "",
    //     xlPercentFromLeft: ""
    // },
    // {
    //     title: "laptop",
    //     altText: "a red industrial sewing machine",
    //     imageHeight: "135px",
    //     percentFromTop: "28%",
    //     percentFromLeft: "30%",
    //     xsHeight: "87px",
    //     xsPercentFromTop: "28%",
    //     xsPercentFromLeft: "30%",
    //     smHeight: "110px",
    //     smPercentFromTop: "28%",
    //     smPercentFromLeft: "30%",
    //     mdHeight: "135px",
    //     mdPercentFromTop: "",
    //     mdPercentFromLeft: "",
    //     lgHeight: "",
    //     lgPercentFromTop: "",
    //     lgPercentFromLeft: "",
    //     xlHeight: "",
    //     xlPercentFromTop: "",
    //     xlPercentFromLeft: ""
    // },
    // {
    //     title: "newspaper",
    //     altText: "an orange newspaper",
    //     imageHeight: "80px",
    //     percentFromTop: "33%",
    //     percentFromLeft: "75%",
    //     xsHeight: "50px",
    //     xsPercentFromTop: "33%",
    //     xsPercentFromLeft: "75%",
    //     smHeight: "70px",
    //     smPercentFromTop: "33%",
    //     smPercentFromLeft: "75%",
    //     mdHeight: "80px",
    //     mdPercentFromTop: "",
    //     mdPercentFromLeft: "",
    //     lgHeight: "",
    //     lgPercentFromTop: "",
    //     lgPercentFromLeft: "",
    //     xlHeight: "",
    //     xlPercentFromTop: "",
    //     xlPercentFromLeft: ""
    // },
    // {
    //     title: "games",
    //     altText: "a brown pair of die on a brown box",
    //     imageHeight: "92px",
    //     percentFromTop: "45%",
    //     percentFromLeft: "65%",
    //     xsHeight: "65px",
    //     xsPercentFromTop: "45%",
    //     xsPercentFromLeft: "65%",
    //     smHeight: "75px",
    //     smPercentFromTop: "",
    //     smPercentFromLeft: "",
    //     mdHeight: "92px",
    //     mdPercentFromTop: "",
    //     mdPercentFromLeft: "",
    //     lgHeight: "",
    //     lgPercentFromTop: "",
    //     lgPercentFromLeft: "",
    //     xlHeight: "",
    //     xlPercentFromTop: "",
    //     xlPercentFromLeft: ""
    // },
    // {
    //     title: "printer",
    //     altText: "a red industrial sewing machine",
    //     imageHeight: "150px",
    //     percentFromTop: "52.5%",
    //     percentFromLeft: "75%",
    //     xsHeight: "105px",
    //     xsPercentFromTop: "52.5%",
    //     xsPercentFromLeft: "75%",
    //     smHeight: "125px",
    //     smPercentFromTop: "",
    //     smPercentFromLeft: "",
    //     mdHeight: "150px",
    //     mdPercentFromTop: "",
    //     mdPercentFromLeft: "",
    //     lgHeight: "",
    //     lgPercentFromTop: "",
    //     lgPercentFromLeft: "",
    //     xlHeight: "",
    //     xlPercentFromTop: "",
    //     xlPercentFromLeft: ""
    // }

]
